services:
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=bottlegame
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - bottlegame
  redis:
    image: "redis:latest"
    networks:
      - bottlegame
  client:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    volumes:
      - "./frontend-react:/app"
      - "/app/node_modules"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - bottlegame
  backend:
    depends_on:
      - database
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_HOST=database
      - DB_NAME=bottlegame
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - TG_TOKEN=6034582865:AAGjXj3BtDq2ynfHfsC_mmIyYD34j7364KU
    networks:
      - bottlegame
networks:
  bottlegame:
    driver: bridge
