FROM node:18.13.0-alpine as build_backend

RUN mkdir /app
WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm ci
COPY . /app
EXPOSE 5000
RUN npm run dev