export enum SocketEvents {
  Connection = "connection",
  ConnectionError = "connect_error",
  Disconnect = "disconnect",
  GameStart = "game:start",
  MessageAdd = "message:add",
  MessageGet = "message:get",
  MessageUpdate = "message:update",
  MessageUpdateAll = "message:update_all",
  RoomGet = "room:get",
  RoomUpdate = "room:update",
  RoomUpdateAll = "room:update_all",
  RoomLeave = "room:leave",
  RoomUserJoin = "room:join",
  RoomUserLeave = "room:leave",
  UsersGet = "users:get",
  UsersUpdateAll = "users:update_all",
}
